# Generated by Django 4.2.30 on 2026-06-16 02:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_id', models.CharField(max_length=255, unique=True)),
                ('field_name', models.CharField(max_length=255)),
                ('path', models.CharField(max_length=255)),
                ('file_url', models.URLField(max_length=500)),
                ('direct_download_url', models.URLField(max_length=500)),
                ('preview_url', models.URLField(max_length=500)),
                ('cached_image', models.ImageField(blank=True, null=True, upload_to='cached_box_images/')),
                ('cache_last_accessed', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SpeciesNetResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('prediction', models.TextField(blank=True)),
                ('prediction_score', models.FloatField(blank=True, null=True)),
                ('prediction_source', models.CharField(blank=True, max_length=255)),
                ('animals', models.JSONField(blank=True, default=list)),
                ('detections', models.JSONField(blank=True, default=list)),
                ('species_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='species_result', to='images.imagerecord')),
            ],
        ),
        migrations.CreateModel(
            name='OCRResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('ocr_texts', models.JSONField(blank=True, default=list)),
                ('temperature_f', models.FloatField(blank=True, null=True)),
                ('capture_date', models.DateField(blank=True, null=True)),
                ('capture_time', models.TimeField(blank=True, null=True)),
                ('capture_datetime', models.DateTimeField(blank=True, null=True)),
                ('image', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ocr_result', to='images.imagerecord')),
            ],
        ),
    ]
