# Generated by Django 4.2.30 on 2026-06-16 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_reseacherprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box_access_token', models.CharField(blank=True, max_length=255)),
                ('box_refresh_token', models.TextField(blank=True, max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='reseacherprofile',
            name='box_access_token',
        ),
        migrations.RemoveField(
            model_name='reseacherprofile',
            name='box_refresh_token',
        ),
    ]
