# Generated by Django 4.2.30 on 2026-06-16 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_appsettings_remove_reseacherprofile_box_access_token_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReseacherProfile',
        ),
    ]
