# Generated by Django 4.2.30 on 2026-06-18 07:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('images', '0005_importjob'),
    ]

    operations = [
        migrations.RenameField(
            model_name='speciesnetresult',
            old_name='species_name',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='imagerecord',
            name='field_name',
        ),
        migrations.AddField(
            model_name='imagerecord',
            name='file_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='appsettings',
            name='box_access_token',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='appsettings',
            name='box_refresh_token',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='imagerecord',
            name='direct_download_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='imagerecord',
            name='file_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='imagerecord',
            name='path',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='imagerecord',
            name='preview_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='importjob',
            name='researcher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ocrresult',
            name='status',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='speciesnetresult',
            name='status',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
