# Generated by Django 4.2.30 on 2026-06-23 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0006_rename_species_name_speciesnetresult_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='box_client_id',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='box_client_secret',
            field=models.TextField(blank=True),
        ),
    ]
