# Generated by Django 4.2.30 on 2026-06-26 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0008_specieslabel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specieslabel',
            name='is_human',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
