# Generated by Django 6.0.6 on 2026-06-27 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0009_alter_specieslabel_is_human'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeciesDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('animal', 'Animal Classification'), ('detection', 'Detector Box')], db_index=True, max_length=50)),
                ('label', models.CharField(blank=True, db_index=True, max_length=255)),
                ('confidence', models.FloatField(blank=True, db_index=True, null=True)),
                ('bbox_x', models.FloatField(blank=True, null=True)),
                ('bbox_y', models.FloatField(blank=True, null=True)),
                ('bbox_width', models.FloatField(blank=True, null=True)),
                ('bbox_height', models.FloatField(blank=True, null=True)),
                ('species_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='species_detections', to='images.speciesnetresult')),
            ],
        ),
    ]
