# Generated by Django 6.0.6 on 2026-07-02 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0011_alter_speciesnetresult_prediction_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SpeciesLabel',
        ),
    ]
