# Generated by Django 4.2.30 on 2026-07-30 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0012_delete_specieslabel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='speciesdetection',
            old_name='confidence',
            new_name='detection_confidence',
        ),
        migrations.RemoveField(
            model_name='speciesdetection',
            name='label',
        ),
        migrations.RemoveField(
            model_name='speciesdetection',
            name='source',
        ),
        migrations.RemoveField(
            model_name='speciesnetresult',
            name='animals',
        ),
        migrations.AddField(
            model_name='speciesdetection',
            name='detection_type',
            field=models.CharField(blank=True, choices=[('animal', 'Animal'), ('human', 'Human'), ('vehicle', 'Vehicle')], db_index=True, max_length=50),
        ),
        migrations.AddField(
            model_name='speciesdetection',
            name='prediction',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='speciesdetection',
            name='prediction_score',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='speciesdetection',
            name='prediction_source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='speciesnetresult',
            name='classifications',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='speciesnetresult',
            name='model_version',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
