# Generated by Django 4.2.30 on 2026-08-12 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0013_rename_confidence_speciesdetection_detection_confidence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagerecord',
            name='contains_human',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
