# Generated by Django 4.2.30 on 2026-08-12 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0014_imagerecord_contains_human'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='box_redirect_uri',
            field=models.URLField(blank=True, help_text='OAuth redirect URI configured in the Box Developer Console.', max_length=500),
        ),
    ]
