# Generated by Django 4.2.30 on 2026-08-13 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0015_appsettings_box_redirect_uri'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appsettings',
            name='box_redirect_uri',
        ),
    ]
